GLOOM = 'gloom'
HARD_ARCHON = 'hard_archon'
HARD_DAMIEN = 'hard_damien'
LOTUS = 'lotus'
LUCID = 'lucid'
NORMAL_DAMIEN = 'normal_damien'
WILL = 'will'

MAX_EXPERIENCE = 10
MIN_EXPERIENCE = 1
VALID_BOSSES = [GLOOM, HARD_ARCHON, HARD_DAMIEN, LOTUS, LUCID, NORMAL_DAMIEN, WILL]

BOSS_VARIANTS_TABLE = [
  [HARD_ARCHON],
  [GLOOM],
  [LOTUS],
  [NORMAL_DAMIEN, HARD_DAMIEN],
  [LUCID],
  [WILL]
]