SCOPES = ["https://www.googleapis.com/auth/spreadsheets.readonly"]
CREDENTIALS_FILE_NAME = 'credentials.json'
TOKEN_ENV = 'MSM_SCHEDULER_TOKEN_JSON'
TOKEN_FILE_NAME = 'token.json'

BASE_TEAMS = 'Base Teams!A1:E'
BOSSES = 'Bosses!A1:G'
PLAYER_AVAILABILITY = 'Player Availability!A1:H'
PLAYER_EXPERIENCES = 'Player Experiences!A1:H'
PLAYER_INTERESTS = 'Player Interests!A1:H'
PLAYERS_SPREADSHEET = 'Players!A1:F'
PLAYER_DISCORD_IDS = 'DiscordIDs!A1:B'
ROLE_CONFIGS = 'RoleConfig!A1:E'

SPREADSHEET_COLUMNS = [
  PLAYERS_SPREADSHEET,
  PLAYER_EXPERIENCES,
  PLAYER_INTERESTS,
  PLAYER_AVAILABILITY,
  PLAYER_DISCORD_IDS,
  BOSSES,
  BASE_TEAMS,
  ROLE_CONFIGS
]